name: PowerShell Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install PowerShell
      shell: bash
      run: |
        # Install PowerShell
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell
    
    - name: Install PSScriptAnalyzer
      shell: pwsh
      run: |
        Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
    
    - name: Lint PowerShell files
      shell: pwsh
      run: |
        $files = Get-ChildItem -Path . -Recurse -Include *.ps1, *.psm1, *.psd1
        if ($files.Count -gt 0) {
          $allResults = $files | ForEach-Object { Invoke-ScriptAnalyzer -Path $_.FullName }
          
          if ($allResults) {
            # Separate errors from warnings
            $errors = $allResults | Where-Object { $_.Severity -eq 'Error' }
            $warnings = $allResults | Where-Object { $_.Severity -ne 'Error' }
            
            # Display all results
            $allResults | Format-Table
            
            # Show summary
            Write-Output "Found $($errors.Count) errors and $($warnings.Count) warnings/info issues"
            
            if ($warnings.Count -gt 0) {
              Write-Output "Warnings and info issues (non-blocking):"
              $warnings | ForEach-Object { Write-Output "  - $($_.RuleName): $($_.Message)" }
            }
            
            # Only fail on errors
            if ($errors.Count -gt 0) {
              Write-Error "PSScriptAnalyzer found $($errors.Count) error(s). Failing the build."
              exit 1
            } else {
              Write-Output "No errors found. Warnings are informational only."
            }
          } else {
            Write-Output "No PowerShell linting issues found."
          }
        } else {
          Write-Output "No PowerShell files found to lint."
        }
